spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    default: dev

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true