spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    default: dev

logging:
  level:
    org.springframework.security: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem